name: Aqua
on: pull_request

env:
  AQUA_USER: ${{ secrets.AQUA_USER }} # Aqua Registry
  AQUA_PASSWORD: ${{ secrets.AQUA_PASSWORD }} # Aqua Registry
  AQUA_TOKEN: ${{ secrets.AQUA_TOKEN }} # Aqua Scanner authentication
  AQUA_HOST: ${{ secrets.AQUA_HOST }} # Aqua Scanner authentication
  DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }} # Docker Registry
  DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }} # Docker Registry
  BUILD_NUMBER: ${{ github.run_id }}
  BUILD_NAME: ${{ github.repository }}
  GITHUB_WORKSPACE: ${{ github.workspace }}
  GH_TOKEN: ${{ secrets.GH_TOKEN }}
  IMAGE_NAME: wrightchin/spring4shell:latest
  # IMAGE_NAME: stanhoe/spring4shell:codetocloud
  
jobs:
  aqua:
    name: Aqua Supply Chain Security
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        
      - name: Setup Aqua Pipeline Enforcer
        uses: aquasecurity/pipeline-enforcer-action@v1.0.0
        env:
          CSPM_URL: https://asia-1.api.cloudsploit.com
          AQUA_URL: https://api.asia-1.supply-chain.cloud.aquasec.com
        with:
          aqua-key: ${{ secrets.AQUA_KEY }}
          aqua-secret: ${{ secrets.AQUA_SECRET }}

      - name: Run Aqua Scanner
        uses: docker://aquasec/aqua-scanner
        with:
          args: trivy fs --sast --format sarif --output trivy-results.sarif --security-checks config,vuln,secret --debug --sast --reachability . 
          # To customize which severities to scan for, add the following flag: --severity UNKNOWN,LOW,MEDIUM,HIGH,CRITICAL
          # To enable SAST scanning, add: --sast
          # To enable npm/dotnet non-lock file scanning, add: --package-json / --dotnet-proj
        env:
          AQUA_KEY: ${{ secrets.AQUA_KEY }}
          AQUA_SECRET: ${{ secrets.AQUA_SECRET }}
          AQUA_URL: https://api.asia-1.supply-chain.cloud.aquasec.com
          CSPM_URL: https://asia-1.api.cloudsploit.com
          TRIVY_RUN_AS_PLUGIN: 'aqua'